### ISSUE TITLE
C Programming/matrix_multiplication.c // more efficient

### ISSUE THREAD

**Issue by tsuyoshi007** [tsuyoshi007/KIT-Batch-6#5]
task: -use function instead repeating the same code

function that you should make : -function for showing matrix
                                                    -function for inputting number to matrix

**Comment by lychunvira18** [comment]
On it, chief!

**Comment by tsuyoshi007** [comment]
you can proceed to do it now :D i'll add comment in a moment

**Comment by tsuyoshi007** [comment]
done adding comment !!!

**Comment by lychunvira18** [comment]
![screenshot 12](https://user-images.githubusercontent.com/47374787/52762663-256b9a00-304b-11e9-99d8-39e5ba356bc7.png)

Would something like this work?
